### PR TITLE
feature/version_handling

### PR DESCRIPTION
**Pull request by edgar-durand**
image

### CODE REVIEW

**Review by phil-booth-qatalog — APPROVED** [review]
Code looks great! Do you think it's possible to add a test case for it to `test/read-value.js`?

No worries if not, I can push one up at the weekend.

**Comment by edgar-durand** [comment]
> Code looks great! Do you think it's possible to add a test case for it to `test/read-value.js`?
> 
> No worries if not, I can push one up at the weekend.

Sure, done.

**Review by phil-booth-qatalog — APPROVED** [review]

**Comment by phil-booth-qatalog** [comment]
Thanks for this, appreciated! I'll publish a new version on npm in the morning. :+1:

**Comment by phil-booth-qatalog** [comment]
Fixes #228.

**Comment by phil-booth-qatalog** [comment]
Published on npm as version `0.8.0`.

**Comment by edgar-durand** [comment]
Awesome ! Thank you.

**Pull request merged**
